Removing warnings
youngnh/parsatron pull request #35
Opened 2018-08-07 20:37 UTC by quoll

This addresses warnings that occurred with ClojureScript. Also, fixed the bencode tests that failed. Updated Clojure, ClojureScript and lein-cljsbuild as the older versions led to warnings.

2018-08-09 14:40 UTC, youngnh requested changes
everything looks excellent here, but I'd suggest a change to `ben-dictionary`. I certainly haven't kept up with the bencode spec https://wiki.theory.org/index.php/BitTorrentSpecification#Bencoding, so I'm not sure if its always been this way, but it looks to me like dictionary keys can only be strings.

If that's the case, then the let-defined `entry` parser should probably change to read a `ben-bytestring` for the key and the return value can continue to use `sorted-map` instead of `sorted-map-by`

2019-09-13 16:54 UTC, quoll commented
Apologies for not getting back to this before now.
Yes, the keys should be keys, which means the parser should be looking for them, rather than testing the map as it gets populated. Done. I also added a few tests for the dictionary.

2019-09-15 14:22 UTC, merged

2019-09-15 14:22 UTC, youngnh commented
merged. cheers!

2019-09-18 15:43 UTC, quoll commented
Curious if you're likely to do a new release at some point? I can put my own on Clojars, but prefer to use the canonical one if it's there :)

2019-09-19 14:45 UTC, youngnh commented
just pushed 0.0.9 which includes this PR 👋

2019-09-19 19:15 UTC, quoll commented
Yay! Thank you!